name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Disable Corepack
        run: corepack disable || true

      - name: Setup PNPM (standalone)
        uses: pnpm/action-setup@v4
        with:
          version: 9
          standalone: true

      - name: Force public npm registry
        run: |
          npm config set registry https://registry.npmjs.org
          echo "registry=https://registry.npmjs.org" >> ~/.npmrc
          pnpm config set registry https://registry.npmjs.org

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build web app
        run: pnpm --filter apps/web build
