name: CI

on:
  push:
    branches: ['main']
  pull_request:

jobs:
  lint-and-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Disable Corepack
        run: corepack disable || true

      - name: Setup PNPM (standalone)
        uses: pnpm/action-setup@v4
        with:
          version: 9
          standalone: true

      - name: Force public npm registry
        run: |
          npm config set registry https://registry.npmjs.org
          echo "registry=https://registry.npmjs.org" >> ~/.npmrc
          pnpm config set registry https://registry.npmjs.org

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run docker health check script
        run: ./scripts/check-health.sh
        continue-on-error: true

      - name: Build
        run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Unit tests with coverage
        run: pnpm test:unit -- --coverage

      - name: Coverage summary
        run: pnpm coverage

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-web
          path: apps/web/coverage

  e2e:
    runs-on: ubuntu-latest
    needs: lint-and-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Disable Corepack
        run: corepack disable || true

      - name: Setup PNPM (standalone)
        uses: pnpm/action-setup@v4
        with:
          version: 9
          standalone: true

      - name: Force public npm registry
        run: |
          npm config set registry https://registry.npmjs.org
          echo "registry=https://registry.npmjs.org" >> ~/.npmrc
          pnpm config set registry https://registry.npmjs.org

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps chromium

      - name: Run E2E tests
        run: pnpm test:e2e
